Loginnav
Eco-Friends-Connect/Eco-Friends pull request #173
Opened 2024-08-15 08:59 UTC by Donnyd88

2024-08-16 23:15 UTC, dinaolmelak requested changes
Thank you for removing the remanence of the old implementation of the logout. ✅
1. The `org-dashboard` logout does not work.
2. I realized that the picture is covering the nav bar on the `userpage`, I think we would need to bring the nav bar to the front and fix it to the top. I will work on that on #169 ticket.

2024-08-16 23:15 UTC, dinaolmelak commented on src/component/welcome-logout/WelcomeLogout.jsx
> +            <li className={styles.a}>Welcome, {firstName}!</li>
Considering we already have welcome on the `org-dashboard` already, can we  remove the `Welcome` here? OR we can add the first name next to the welcome found on the `org-dashboard` and then have this to just have the logout button.

2024-08-17 20:37 UTC, dinaolmelak requested changes
Branch update needed

2024-08-17 20:37 UTC, dinaolmelak commented on .gitignore
> +/backend/.env.production
There is no backend `.env.production` file

2024-08-17 20:39 UTC, dinaolmelak commented
I saw that the functionality works for the `org-dashboard`, It should work for the `userpage` too but it is not working. I will review after the branch updates

2024-08-18 00:04 UTC, Donnyd88 commented
> I saw that the functionality works for the `org-dashboard`, It should work for the `userpage` too but it is not working. I will review after the branch updates

Do you want me to add the navbar to the userpage?

2024-08-18 01:07 UTC, dinaolmelak commented
I believe userpage already has a navbar

2024-08-18 01:09 UTC, Donnyd88 commented
> I believe userpage already has a navbar

It did not. Or rather the NavBar component on the other pages that contained the welcome message and login button wasn't on that page. I just added it, though.

2024-08-18 02:16 UTC, dinaolmelak approved these changes

2024-08-18 02:21 UTC, merged